### ISSUE TITLE
Fix bug where liveness probe doesn't render correctly in Starlark code generator

### ISSUE THREAD

**Issue by jonnylangefeld** [cruise-automation/isopod#53]
A liveness probe like
```yaml
livenessProbe:
  httpGet:
    path: /healthz
    port: 8080
    scheme: HTTPS
```
renders incorrectly to 
```python
livenessProbe=corev1.Probe(
),
```
