### ISSUE TITLE
Code generator bugs

### ISSUE THREAD

**Issue by jonnylangefeld** [cruise-automation/isopod#63]
This is a thread to collect edge cases where the code generator doesn't produce the desired outcome.
Each of these should be covered in a test case when resolved.

1. Currently the starlark code generator doesn't correctly render resource limits and requests:
YAML:
```
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
```
Starlark:
```
                            resources=corev1.ResourceRequirements(
                                limits={
                                    "cpu": apiresource.Quantity(
                                    ),
                                    "memory": apiresource.Quantity(
                                    )
                                },
                                requests={
                                    "cpu": apiresource.Quantity(
                                    ),
                                    "memory": apiresource.Quantity(
                                    )
                                }
                            ),
```

2. a string in a liveness probe can't get applied:
YAML:
```
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
```
Starlark:
```
                            livenessProbe=corev1.Probe(
                                handler=corev1.Handler(
                                    httpGet=corev1.HTTPGetAction(
                                        path="/healthy",
                                        port=utilintstr.IntOrString(
                                            type=1,
                                            strVal="http"
                                        ),
                                    ),
                                ),
                                initialDelaySeconds=10,
                                periodSeconds=30,
                            ),
```
Error:
```
E0710 14:26:13.059890   21531 main.go:243] addons run failed: `install' execution failed: failed addon installation: <addon: kafka-operator> run failed: TypeError: value 1 (type `int') can't be assigned to type `"k8s.io/apimachinery/pkg/util/intstr".Type'.
```

3. raw JSON isn't rendered correctly:
YAML:
```
          properties:
            authentication:
              type: object
              properties:
                type:
                  type: string
                  enum:
                    - tls
                    - scram-sha-512
                  description: Authentication type.
              required:
                - type
              description: Authentication mechanism enabled for this Kafka user.
```
Starlark:
```
                                properties={
                                    "authentication": apiextensionsv1beta1.JSONSchemaProps(
                                        description="Authentication mechanism enabled for this Kafka user.",
                                        type="object",
                                        required=["type"],
                                        properties={
                                            "type": apiextensionsv1beta1.JSONSchemaProps(
                                                description="Authentication type.",
                                                type="string",
                                                enum=[apiextensionsv1beta1.JSON(
                                                    raw="InRscyI="
                                                ),
                                                apiextensionsv1beta1.JSON(
                                                    raw="InNjcmFtLXNoYS01MTIi"
                                                )],
                                            )
                                        },
                                    ),
```

The above issues came up during generating the [strimzi kafka controller](https://strimzi.io/install/latest?namespace=kafka)
